version: '3.8'

services:
  server:
    build: ./
    command: ./go-app
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    restart: always
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

volumes:
  postgres-data: